/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvButton: typeof import('./ui/SvButton.vue')['default']
    SvCard: typeof import('./ui/SvCard.vue')['default']
    SvField: typeof import('./ui/SvField.vue')['default']
  }
}
